# Generated by Django 5.1.2 on 2024-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='status',
            field=models.CharField(default='listed'),
        ),
    ]
