# Generated by Django 5.1 on 2024-11-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='variant_videos/'),
        ),
    ]
