# Generated by Django 5.1 on 2024-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_variants_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='variant_videos/'),
        ),
    ]
